### ISSUE TITLE
failed to run preprocess.py, missing meeting_id and meeting_transcripts expects list of str

### ISSUE THREAD

**Issue by md-experiments** [salesforce/query-focused-sum#2]
Hello there, thank you for a great paper and piece of work! 

I tried to train multiencoder, but when I try to get raw data from https://github.com/Yale-LILY/QMSum, it seems to have a slightly different format

Failed to run preprocess.py, missing meeting_id and meeting_transcripts expects list of str but the oroginal data has list of dict

I can hack around and change to format to introduce dummy meeting_id and make it look as expected but I wanted to first check if I am missing something or if there is an cleaner way to do so.

Question is: before running preprocess.py should one just get the jsonl files from  https://github.com/Yale-LILY/QMSum or is there additional and different data expected beyond a simple transform to the original data?

Thank you in advance!

**Comment by Alex-Fabbri** [comment]
Hi @md-experiments 

Thank you for pointing this out! We have added steps for preprocessing the QMSum data [here](https://github.com/salesforce/query-focused-sum/blob/master/preprocessing/README.md).

Feel free to reopen the issue if there are any other related questions.

**Comment by 731935354** [comment]
@Alex-Fabbri There is no folder "data" so the command `python convert_qmsum.py` can not run directly. The default filename for each split "{split}-meetings.jsonl" is not provided in the official QMSum dataset. Could you please give more hints on how to obtain train/dev/test-meeting.jsonl files?

Thanks!
